org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
mapping_version=2024.11.17
minecraft_version_range=[1.2,1.21.1)
neo_version=21.1.249
neo_version_range=[21,)
loader_version_range=[4,)

mod_id=tempusetchaos
mod_name=Tempus Et Chaos
mod_license=GNU GPL 3.0
mod_version=0.0.1-alpha.1
mod_group_id=org.moshang
mod_authors=moshang
mod_description=
